#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication_token:
  path: /api/login
  methods: ['POST']

register:
  path: /api/register
  controller: App\Core\Authentication\RegisterController::onRegister