#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
  path: /api/login
  methods: ['POST']

register:
  path: /api/register
  methods: ['POST']
  controller: App\Core\Authentication\RegisterController::onRegister